### ISSUE TITLE
errors when converting .lis files

### ISSUE THREAD

**Issue by morgothsvoidpointer** [paulross/TotalDepth#23]
I am getting an error converting a folder of .lis files on running the function TotalDepth.LIS.core.File.FileRead(path_to_file)

three of the files give error 

File "/anaconda3/lib/python3.7/site-packages/TotalDepth/LIS/core/FileIndexer.py", line 451, in __init__
    fn = self._despatchLrType[lrTy]

KeyError: 78

the last one gives 

File "/anaconda3/lib/python3.7/site-packages/TotalDepth/LIS/core/TifMarker.py", line 163, in reportError
    raise ExceptionTifMarker(theMsg)

ExceptionTifMarker: TIF read() expected 0x98, got tell: 0x96, Shortfall: 0x2

Any ideas? The files are .lis files from the OGA database https://ndr.ogauthority.co.uk - I've uploaded one of them if it helps https://github.com/morgothsvoidpointer/hello-world/blob/master/11_30a-B11_dwl_DWL_MWD_317972493.lis

**Comment by paulross** [comment]
Thanks for reporting this and, in particular, for supplying an example file. That file has the two problems that you mentioned, firstly at 0x176 I see this:

```
00000170: 2020 2e30 3030 0000 0000 2c01 0000 a004    .000....,.....
00000180: 0000 031d 0000 4e00 4449 534b 4649 4c45  ......N.DISKFILE
```

At 0x176 there are the three TIF words (12 bytes) followed by the Physical Record Header (4 bytes `0x031d 0000`) then the logical record header (`0x4e00`). This is Logical Record type decimal 78 which does not exist in the standard so the file indexer throws an exception.

I have made a one line fix to issue a warning instead and released TotalDepth as version 0.3.2 on PyPi for Python version 3.6+. As well as the source there are the pre-built wheels there for Mac OS X [https://pypi.org/project/TotalDepth/#files](https://pypi.org/project/TotalDepth/#files).

The second problem with that file is that there is one byte (`0x00`) Physical Record padding at `0x49f`:

```
00000490: 3d4a 756c 526f 620d 0a24 454f 460d 0a00  =JulRob..$EOF...
000004a0: 0000 0000 7601 0000 cc07 0000 0320 0001  ....v........ ..
```

This file has TIF markers and those can be used to detect this padding but this only happens if `keepGoing=True` is supplied to `TotalDepth.LIS.core.File.FileRead` which means 'ignore deviations from the standard if necessary'. Here is an example: [https://totaldepth.readthedocs.io/en/latest/ref/LIS/core/FileIndexer.html](https://totaldepth.readthedocs.io/en/latest/ref/LIS/core/FileIndexer.html)

The command line tools usually have a `-k` or `--keep-going` option to do this. For example, on your file:

```
$ tdlisscanphysrec 11_30a-B11_dwl_DWL_MWD_317972493.lis
Cmd: ~/pyenvs/TotalDepth_GitHub_3.7_A/bin/tdlisscanphysrec 11_30a-B11_dwl_DWL_MWD_317972493.lis
TIF     ?  :        Type        Back        Next  PR:     tell()  Length    Attr  LD_len  RecNum  FilNum  ChkSum   LR Attr [Total LD]
--------------------------------------------------------------- start ---------------------------------------------------------------
TIF  True >:  0x       0  0x       0  0x      90  PR: 0x       0     132  0x   0     128  ------  ------  ------ 0x84 0x00 [     128]
TIF  True >:  0x       0  0x       0  0x     120  PR: 0x      90     132  0x   0     128  ------  ------  ------ 0x82 0x00 [     128]
TIF  True >:  0x       0  0x     120  0x     176  PR: 0x     120      62  0x   0      58  ------  ------  ------ 0x80 0x00 [      58]
TIF  True >:  0x       0  0x     12c  0x     4a0  PR: 0x     176     797  0x   0     793  ------  ------  ------ 0x4E 0x00
Traceback (most recent call last):
8<---- snip ---->8
TotalDepth.LIS.core.TifMarker.ExceptionTifMarker: TIF read() expected 0x4A0, got tell: 0x49F, Shortfall: 0x1
```

Adding `--keep-going` fixes this:

```
$ tdlisscanphysrec 11_30a-B11_dwl_DWL_MWD_317972493.lis --keep-going
Cmd: ~/pyenvs/TotalDepth_GitHub_3.7_A/bin/tdlisscanphysrec 11_30a-B11_dwl_DWL_MWD_317972493.lis --keep-going
TIF     ?  :        Type        Back        Next  PR:     tell()  Length    Attr  LD_len  RecNum  FilNum  ChkSum   LR Attr [Total LD]
--------------------------------------------------------------- start ---------------------------------------------------------------
TIF  True >:  0x       0  0x       0  0x      90  PR: 0x       0     132  0x   0     128  ------  ------  ------ 0x84 0x00 [     128]
TIF  True >:  0x       0  0x       0  0x     120  PR: 0x      90     132  0x   0     128  ------  ------  ------ 0x82 0x00 [     128]
TIF  True >:  0x       0  0x     120  0x     176  PR: 0x     120      62  0x   0      58  ------  ------  ------ 0x80 0x00 [      58]
TIF  True >:  0x       0  0x     12c  0x     4a0  PR: 0x     176     797  0x   0     793  ------  ------  ------ 0x4E 0x002021-01-30 09:49:22,164 WARNING  TifMarkerRead: tell 0x49f making up PR padding of 0x1 by seeking to 0x4a0
 [     793]
TIF  True >:  0x       0  0x     176  0x     7cc  PR: 0x     4a0     800  0x   1     796  ------  ------  ------ 0x22 0x00
TIF  True >:  0x       0  0x     4a0  0x     af8  PR: 0x     7cc     800  0x   3     796  ------  ------  ------ + --   --
TIF  True >:  0x       0  0x     7cc  0x     e24  PR: 0x     af8     800  0x   2     796  ------  ------  ------ + --   -- [    2388]
TIF  True >:  0x       0  0x     af8  0x    11a4  PR: 0x     e24     884  0x   0     880  ------  ------  ------ 0x22 0x00 [     880]
```

I have a fairly major release coming up whenever I get time to do it that fixes all these problems, particularly LIS Physical Record Padding.

Let me know if version 0.3.2 and `keepGoing=True` / `--keep-going` works for you.

**Comment by morgothsvoidpointer** [comment]
Hi! Thanks very much - it does seem to run without error now for the first error I mentioned.

The last file however wouldn't give in so easily... so here's my code


import TotalDepth
from TotalDepth.LIS.core import File
from TotalDepth.LIS.core import FileIndexer
from TotalDepth.LIS.core import LogiRec
import csv
import numpy as np
import pandas as pd
import os
            lis_file = File.FileRead(source_dir+filename, keepGoing=True)

            lis_index = FileIndexer.FileIndex(lis_file)
            
            cons_records = [lr for lr in lis_index.genAll() if lr.lrType in LogiRec.LR_TYPE_TABLE_DATA]
            for i in range(len(cons_records)):
                lis_file.seekLr(cons_records[i].tell)
                table = LogiRec.LrTableRead(lis_file)
                table_meta=[]
                for row in table.genRows():
                    row_np=[]
                    for col in row.genCells():
                        #print(col.value, ' ', end='')
                        #print()
                        row_np.append(col.value)
                    table_meta.append(row_np)
                table_np=np.array(table_meta)
                print(table_np)
            log_passes = list(lis_index.genLogPasses())
            for i in range(len(log_passes)):
                log_passes[i].logPass.setFrameSet(lis_file)            
                data = log_passes[i].logPass.frameSet.frames
                
                col_labels_list=list(log_passes[i].logPass.genFrameSetScNameUnit())
                cols_labels=[collab[0]+" ["+collab[1]+"]" for collab in col_labels_list]
                
                filename_new=filename.split(sep="/")[-1].split(sep=".")[0]+"_"+str(i)+".csv"
                fp_new=open(data_dir+filename_new,"w")
                w=csv.writer(fp_new,delimiter=',')
                w.writerow(cols_labels)
                for row in data:
                    w.writerow(row)
                    
                fp_new.close()

here is the error message


  File "<ipython-input-105-155ae65dd349>", line 22, in <module>
    log_passes[i].logPass.setFrameSet(lis_file)

  File "/home/deepthought42/anaconda3/lib/python3.7/site-packages/TotalDepth/LIS/core/LogPass.py", line 555, in setFrameSet
    raise ExceptionLogPass('LogPass.setFrameSet(): no frames to load.')

ExceptionLogPass: LogPass.setFrameSet(): no frames to load.

and here is the file

https://github.com/morgothsvoidpointer/hello-world/blob/master/109_05-_1_dwl_DWL_MWD_1670386.lis

It seems that it is unable to find any actual decipherable data (the metadata retrieved with cons_records seems to be fine).

**Comment by paulross** [comment]
Your are so nearly there!

What is happening is this file has duplicate Data Format Specification Records (DFSRs). Why some programs write these duplicates is beyond me.

A log pass is defined as a DFSR with *possibly* a Frame Set (some frame data), here is the [documentation](https://totaldepth.readthedocs.io/en/latest/usage/lis.html#log-pass). TotalDepth sees the first DFSR but there is no frame data with it so when you try `log_passes[i].logPass.setFrameSet(lis_file)` it throws an Exception. The second DFSR *does* have frame data following it so that call will succeed.

You just need a minor change to your code to include a test to see if there is any frame data associated with the Log Pass:

```python
    if log_passes[i].logPass.totalFrames > 0:
        log_passes[i].logPass.setFrameSet(lis_file)
        # Your code here...
```

I've made a note to improve the documentation about this. FWIW there is a command line tool `tdlistohtml` which is useful to run on problem files as it gives you a fairly visual impression of the file. In your case:

```
$ tdlistohtml -k 109_05-_1_dwl_DWL_MWD_1670386.lis 109_05-_1_dwl_DWL_MWD_1670386.lis.html
```

This generates an HTML file that is easy to browse.

I'll close this issue now but feel free to raise another one if you have any problems.
